import type { Metadata } from 'next';
import type { ReactElement } from 'react';

import { Inter } from 'next/font/google';
import Link from 'next/link';

import styles from './Layout.module.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.layout}>
          <nav>
            <ul className={styles.list}>
              <li>
                <Link className={styles.link} href="/">
                  Hook Simple
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/hook-double">
                  Hook Double
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/hook-dynamic">
                  Hook Dynamic
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/hook-fields">
                  Hook Fields
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/hook-lib">
                  Hook Lib
                </Link>
              </li>
            </ul>
            <ul className={styles.list}>
              <li>
                <Link className={styles.link} href="/component-simple">
                  Component Simple
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/component-double">
                  Component Double
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/component-dynamic">
                  Component Dynamic
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/component-fields">
                  Component Fields
                </Link>
              </li>
              <li>
                <Link className={styles.link} href="/component-lib">
                  Component Lib
                </Link>
              </li>
            </ul>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
